version: '3'
services:
  backend:
    build:
      context: ./services-flask
      dockerfile: ./Dockerfile
    restart: always
    ports:
     - "5000:5000"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8080:5000"
