FROM python:3.8
RUN mkdir /Flask
COPY . /Flask
WORKDIR /Flask
EXPOSE 5000
RUN pip install librosa && pip install keras && pip install tensorflow && pip install numpy  && pip install scikit-learn  && pip install flask  && pip install pillow 
CMD ["python", "app.py"]